package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AlternateIdentifiers generated by hbm2java
 */
@Entity
@Table(name = "alternate_identifiers")
public class AlternateIdentifiers implements java.io.Serializable {

	private int alternateIdentifiersId;
	private Resources resources;
	private String alternateIdentifier;
	
	public AlternateIdentifiers() {
	}

	public AlternateIdentifiers(Resources resources,String alternateIdentifier) {
		this.resources = resources;
		this.alternateIdentifier = alternateIdentifier;
	}

	@Id
	@Column(name = "alternate_identifiers_id", unique = true, nullable = false)
	@SequenceGenerator(name="alternate_identifiers_id_seq",schema="version30",sequenceName="alternate_identifiers_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="alternate_identifiers_id_seq")
	public int getAlternateIdentifiersId() {
		return this.alternateIdentifiersId;
	}

	public void setAlternateIdentifiersId(int alternateIdentifiersId) {
		this.alternateIdentifiersId = alternateIdentifiersId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_identifier")
	@JsonIgnore
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	@Column(name = "alternate_identifier")
	public String getAlternateIdentifier() {
		return this.alternateIdentifier;
	}

	public void setAlternateIdentifier(String alternateIdentifier) {
		this.alternateIdentifier = alternateIdentifier;
	}

}
