package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Collectors generated by hbm2java
 */
@Entity
@Table(name = "collectors")
public class Collectors implements java.io.Serializable {

	private int collectorId;
	private CvIdentifierType cvIdentifierType;
	private Resources resources;
	private String collectorName;
	private String collectorIdentifier;

	public Collectors() {
	}

	

	public Collectors(Resources resources,
			CvIdentifierType cvIdentifierType,
			String collectorName,
			String collectorIdentifier) {		
		this.cvIdentifierType = cvIdentifierType;
		this.resources = resources;
		this.collectorName = collectorName;
		this.collectorIdentifier = collectorIdentifier;
	}

	@Id
	@Column(name = "collector_id", unique = true, nullable = false)
	@SequenceGenerator(name="collector_id_seq",schema="version30",sequenceName="collector_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="collector_id_seq")
	public int getCollectorId() {
		return this.collectorId;
	}

	public void setCollectorId(int collectorId) {
		this.collectorId = collectorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "collector_identifier_type")
	public CvIdentifierType getCvIdentifierType() {
		return this.cvIdentifierType;
	}

	public void setCvIdentifierType(CvIdentifierType cvIdentifierType) {
		this.cvIdentifierType = cvIdentifierType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_identifier")
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	@Column(name = "collector_name")
	public String getCollectorName() {
		return this.collectorName;
	}

	public void setCollectorName(String collectorName) {
		this.collectorName = collectorName;
	}

	@Column(name = "collector_identifier")
	public String getCollectorIdentifier() {
		return this.collectorIdentifier;
	}

	public void setCollectorIdentifier(String collectorIdentifier) {
		this.collectorIdentifier = collectorIdentifier;
	}

}
