package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvIdentifierType generated by hbm2java
 */
@Entity
@Table(name = "cv_identifier_type")
public class CvIdentifierType implements java.io.Serializable {

	private int cvIdentifierTypeId;
	private String identifierType;
	private Set<RelatedResources> relatedResourceses = new HashSet<RelatedResources>(
			0);
	private Set<Collectors> collectorses = new HashSet<Collectors>(0);
	private Set<Contributors> contributorses = new HashSet<Contributors>(0);

	public CvIdentifierType() {
	}

	public CvIdentifierType(int cvIdentifierTypeId) {
		this.cvIdentifierTypeId = cvIdentifierTypeId;
	}

	public CvIdentifierType(int cvIdentifierTypeId, String identifierType,
			Set<RelatedResources> relatedResourceses,
			Set<Collectors> collectorses, Set<Contributors> contributorses) {
		this.cvIdentifierTypeId = cvIdentifierTypeId;
		this.identifierType = identifierType;
		this.relatedResourceses = relatedResourceses;
		this.collectorses = collectorses;
		this.contributorses = contributorses;
	}

	@Id
	@Column(name = "cv_identifier_type_id", unique = true, nullable = false)
	public int getCvIdentifierTypeId() {
		return this.cvIdentifierTypeId;
	}

	public void setCvIdentifierTypeId(int cvIdentifierTypeId) {
		this.cvIdentifierTypeId = cvIdentifierTypeId;
	}

	@Column(name = "identifier_type")
	public String getIdentifierType() {
		return this.identifierType;
	}

	public void setIdentifierType(String identifierType) {
		this.identifierType = identifierType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvIdentifierType")
	public Set<RelatedResources> getRelatedResourceses() {
		return this.relatedResourceses;
	}

	public void setRelatedResourceses(Set<RelatedResources> relatedResourceses) {
		this.relatedResourceses = relatedResourceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvIdentifierType")
	public Set<Collectors> getCollectorses() {
		return this.collectorses;
	}

	public void setCollectorses(Set<Collectors> collectorses) {
		this.collectorses = collectorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvIdentifierType")
	public Set<Contributors> getContributorses() {
		return this.contributorses;
	}

	public void setContributorses(Set<Contributors> contributorses) {
		this.contributorses = contributorses;
	}

}
