package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvMaterialTypes generated by hbm2java
 */
@Entity
@Table(name = "cv_material_types")
public class CvMaterialTypes implements java.io.Serializable {

	private int cvMaterialTypeId;
	private String materialType;
	private Set<MaterialTypes> materialTypeses = new HashSet<MaterialTypes>(0);

	public CvMaterialTypes() {
	}

	public CvMaterialTypes(int cvMaterialTypeId) {
		this.cvMaterialTypeId = cvMaterialTypeId;
	}

	public CvMaterialTypes(int cvMaterialTypeId, String materialType,
			Set<MaterialTypes> materialTypeses) {
		this.cvMaterialTypeId = cvMaterialTypeId;
		this.materialType = materialType;
		this.materialTypeses = materialTypeses;
	}

	@Id
	@Column(name = "cv_material_type_id", unique = true, nullable = false)
	public int getCvMaterialTypeId() {
		return this.cvMaterialTypeId;
	}

	public void setCvMaterialTypeId(int cvMaterialTypeId) {
		this.cvMaterialTypeId = cvMaterialTypeId;
	}

	@Column(name = "material_type", length = 100)
	public String getMaterialType() {
		return this.materialType;
	}

	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvMaterialTypes")
	public Set<MaterialTypes> getMaterialTypeses() {
		return this.materialTypeses;
	}

	public void setMaterialTypeses(Set<MaterialTypes> materialTypeses) {
		this.materialTypeses = materialTypeses;
	}

}
