package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvMaterialTypes generated by hbm2java
 */
@Entity
@Table(name = "cv_material_types")
@NamedQueries({
	@NamedQuery(
			name="CvMaterialTypes.listAll",
		    query="SELECT cmt FROM CvMaterialTypes cmt"
	)
})
public class CvMaterialTypes implements java.io.Serializable {

	private int cvMaterialTypeId;
	private String materialType;
	

	public CvMaterialTypes() {
	}

	public CvMaterialTypes(int cvMaterialTypeId) {
		this.cvMaterialTypeId = cvMaterialTypeId;
	}

	public CvMaterialTypes(int cvMaterialTypeId, String materialType) {
		this.cvMaterialTypeId = cvMaterialTypeId;
		this.materialType = materialType;
		
	}

	@Id
	@Column(name = "cv_material_type_id", unique = true, nullable = false)
	public int getCvMaterialTypeId() {
		return this.cvMaterialTypeId;
	}

	public void setCvMaterialTypeId(int cvMaterialTypeId) {
		this.cvMaterialTypeId = cvMaterialTypeId;
	}

	@Column(name = "material_type", length = 100)
	public String getMaterialType() {
		return this.materialType;
	}

	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}



}
