package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvResourceType generated by hbm2java
 */
@Entity
@Table(name = "cv_resource_type")
@NamedQueries({
	@NamedQuery(
			name="CvResourceType.listAll",
		    query="SELECT crt FROM CvResourceType crt"
	),
	@NamedQuery(
			name="CvResourceType.search",
		    query="SELECT crt FROM CvResourceType crt where lower(crt.resourceType) = lower(:resourceType)"
	)
})
public class CvResourceType implements java.io.Serializable {

	private int cvResourceTypeId;
	private String resourceType;
	

	public CvResourceType() {
	}

	public CvResourceType(int cvResourceTypeId) {
		this.cvResourceTypeId = cvResourceTypeId;
	}

	public CvResourceType(int cvResourceTypeId, String resourceType) {
		this.cvResourceTypeId = cvResourceTypeId;
		this.resourceType = resourceType;
		
	}

	@Id
	@Column(name = "cv_resource_type_id", unique = true, nullable = false, insertable=false)
	public int getCvResourceTypeId() {
		return this.cvResourceTypeId;
	}

	public void setCvResourceTypeId(int cvResourceTypeId) {
		this.cvResourceTypeId = cvResourceTypeId;
	}

	@Column(name = "resource_type")
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	

}
