package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.vividsolutions.jts.geom.Geometry;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location")
public class Location implements java.io.Serializable {

	private int locationId;
	private String locality;
	private String localityUri;
	private String srid;
	private String verticalDatum;
	private String geometryUri;
	private Geometry geometry;
	private Set<Resources> resourceses = new HashSet<Resources>(0);

	public Location() {
	}

	public Location(int locationId) {
		this.locationId = locationId;
	}

	public Location(int locationId, String locality, String localityUri,
			String srid, String verticalDatum, String geometryUri,
			Geometry geometry, Set<Resources> resourceses) {
		this.locationId = locationId;
		this.locality = locality;
		this.localityUri = localityUri;
		this.srid = srid;
		this.verticalDatum = verticalDatum;
		this.geometryUri = geometryUri;
		this.geometry = geometry;
		this.resourceses = resourceses;
	}

	@Id
	@Column(name = "location_id", unique = true, nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	@Column(name = "locality")
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "locality_uri")
	public String getLocalityUri() {
		return this.localityUri;
	}

	public void setLocalityUri(String localityUri) {
		this.localityUri = localityUri;
	}

	@Column(name = "srid")
	public String getSrid() {
		return this.srid;
	}

	public void setSrid(String srid) {
		this.srid = srid;
	}

	@Column(name = "vertical_datum")
	public String getVerticalDatum() {
		return this.verticalDatum;
	}

	public void setVerticalDatum(String verticalDatum) {
		this.verticalDatum = verticalDatum;
	}

	@Column(name = "geometry_uri")
	public String getGeometryUri() {
		return this.geometryUri;
	}

	public void setGeometryUri(String geometryUri) {
		this.geometryUri = geometryUri;
	}

	@Column(name = "geometry")
	public Serializable getGeometry() {
		return this.geometry;
	}

	public void setGeometry(Geometry geometry) {
		this.geometry = geometry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<Resources> getResourceses() {
		return this.resourceses;
	}

	public void setResourceses(Set<Resources> resourceses) {
		this.resourceses = resourceses;
	}

}
