package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogDate generated by hbm2java
 */
@Entity
@Table(name = "log_date")
public class LogDate implements java.io.Serializable {

	private int logDateId;
	private String eventType;
	private Date logDate;
	private Set<Resources> resourceses = new HashSet<Resources>(0);

	public LogDate() {
	}

	public LogDate(int logDateId) {
		this.logDateId = logDateId;
	}

	public LogDate(int logDateId, String eventType, Date logDate,
			Set<Resources> resourceses) {
		this.logDateId = logDateId;
		this.eventType = eventType;
		this.logDate = logDate;
		this.resourceses = resourceses;
	}

	@Id
	@Column(name = "log_date_id", unique = true, nullable = false)
	public int getLogDateId() {
		return this.logDateId;
	}

	public void setLogDateId(int logDateId) {
		this.logDateId = logDateId;
	}

	@Column(name = "event_type")
	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "log_date", length = 29)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logDate")
	public Set<Resources> getResourceses() {
		return this.resourceses;
	}

	public void setResourceses(Set<Resources> resourceses) {
		this.resourceses = resourceses;
	}

}
