package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MaterialTypes generated by hbm2java
 */
@Entity
@Table(name = "material_types")
public class MaterialTypes implements java.io.Serializable {

	private int materialTypesId;
	private CvMaterialTypes cvMaterialTypes;
	private Resources resources;

	public MaterialTypes() {
	}

	public MaterialTypes(int materialTypesId) {
		this.materialTypesId = materialTypesId;
	}

	public MaterialTypes(int materialTypesId, CvMaterialTypes cvMaterialTypes,
			Resources resources) {
		this.materialTypesId = materialTypesId;
		this.cvMaterialTypes = cvMaterialTypes;
		this.resources = resources;
	}

	@Id
	@Column(name = "material_types_id", unique = true, nullable = false)
	public int getMaterialTypesId() {
		return this.materialTypesId;
	}

	public void setMaterialTypesId(int materialTypesId) {
		this.materialTypesId = materialTypesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "material_type")
	public CvMaterialTypes getCvMaterialTypes() {
		return this.cvMaterialTypes;
	}

	public void setCvMaterialTypes(CvMaterialTypes cvMaterialTypes) {
		this.cvMaterialTypes = cvMaterialTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_identifier")
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

}
