package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MaterialTypes generated by hbm2java
 */
@Entity
@Table(name = "material_types")
public class MaterialTypes implements java.io.Serializable {

	private int materialTypesId;
	private CvMaterialTypes cvMaterialTypes;
	private Resources resources;

	public MaterialTypes() {
	}


	public MaterialTypes(Resources resources, CvMaterialTypes cvMaterialTypes) {		
		this.cvMaterialTypes = cvMaterialTypes;
		this.resources = resources;
	}

	@Id
	@Column(name = "material_types_id", unique = true, nullable = false)
	@SequenceGenerator(name="material_types_id_seq",schema="version30",sequenceName="material_types_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="material_types_id_seq")
	public int getMaterialTypesId() {
		return this.materialTypesId;
	}

	public void setMaterialTypesId(int materialTypesId) {
		this.materialTypesId = materialTypesId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "material_type")	
	public CvMaterialTypes getCvMaterialTypes() {
		return this.cvMaterialTypes;
	}

	public void setCvMaterialTypes(CvMaterialTypes cvMaterialTypes) {
		this.cvMaterialTypes = cvMaterialTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_identifier")
	@JsonIgnore
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

}
