package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Prefix generated by hbm2java
 */
@Entity
@Table(name = "prefix")
public class Prefix implements java.io.Serializable {

	private int id;
	private Integer version;
	private String prefix;
	private Date created;
	private Set<Allocator> allocators = new HashSet<Allocator>(0);
	private Set<Registrant> registrants = new HashSet<Registrant>(0);

	public Prefix() {
	}

	public Prefix(int id, String prefix) {
		this.id = id;
		this.prefix = prefix;
	}

	public Prefix(int id, String prefix, Date created,
			Set<Allocator> allocators, Set<Registrant> registrants) {
		this.id = id;
		this.prefix = prefix;
		this.created = created;
		this.allocators = allocators;
		this.registrants = registrants;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "prefix", nullable = false, length = 15)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "allocator_prefixes", joinColumns = { @JoinColumn(name = "prefixes", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "allocator", nullable = false, updatable = false) })
	public Set<Allocator> getAllocators() {
		return this.allocators;
	}

	public void setAllocators(Set<Allocator> allocators) {
		this.allocators = allocators;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "registrant_prefixes", joinColumns = { @JoinColumn(name = "prefixes", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "registrant", nullable = false, updatable = false) })
	public Set<Registrant> getRegistrants() {
		return this.registrants;
	}

	public void setRegistrants(Set<Registrant> registrants) {
		this.registrants = registrants;
	}

}
