package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * RelatedResources generated by hbm2java
 */
@Entity
@Table(name = "related_resources")
public class RelatedResources implements java.io.Serializable {

	private int relatedResourceId;
	private CvIdentifierType cvIdentifierType;
	private Resources resources;
	private String relatedResource;
	private String relationType;

	public RelatedResources() {
	}

	

	public RelatedResources(Resources resources,
			CvIdentifierType cvIdentifierType, 
			String relatedResource, String relationType) {		
		this.cvIdentifierType = cvIdentifierType;
		this.resources = resources;
		this.relatedResource = relatedResource;
		this.relationType = relationType;
	}

	@Id
	@Column(name = "related_resource_id", unique = true, nullable = false)
	@SequenceGenerator(name="related_resource_id_seq",schema="version30",sequenceName="related_resource_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="related_resource_id_seq")
	public int getRelatedResourceId() {
		return this.relatedResourceId;
	}

	public void setRelatedResourceId(int relatedResourceId) {
		this.relatedResourceId = relatedResourceId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "related_resource_identifier_type")
	public CvIdentifierType getCvIdentifierType() {
		return this.cvIdentifierType;
	}

	public void setCvIdentifierType(CvIdentifierType cvIdentifierType) {
		this.cvIdentifierType = cvIdentifierType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_identifier")
	@JsonIgnore
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	@Column(name = "related_resource")
	public String getRelatedResource() {
		return this.relatedResource;
	}

	public void setRelatedResource(String relatedResource) {
		this.relatedResource = relatedResource;
	}

	@Column(name = "relation_type")
	public String getRelationType() {
		return this.relationType;
	}

	public void setRelationType(String relationType) {
		this.relationType = relationType;
	}

}
