package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ResourceDate generated by hbm2java
 */
@Entity
@Table(name = "resource_date")
public class ResourceDate implements java.io.Serializable {

	private int resourceDateId;
	private String timeInstant;
	private String timePeriodStart;
	private String timePeriodEnd;


	public ResourceDate() {
	}


	public ResourceDate(String timeInstant,
			String timePeriodStart, String timePeriodEnd) {	
		this.timeInstant = timeInstant;
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = timePeriodEnd;	
	}

	@Id
	@Column(name = "resource_date_id", unique = true, nullable = false)
	@SequenceGenerator(name="resource_date_id_seq",schema="version30",sequenceName="resource_date_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="resource_date_id_seq")
	public int getResourceDateId() {
		return this.resourceDateId;
	}

	public void setResourceDateId(int resourceDateId) {
		this.resourceDateId = resourceDateId;
	}

	
	@Column(name = "time_instant", length = 29)
	public String getTimeInstant() {
		return this.timeInstant;
	}

	public void setTimeInstant(String timeInstant) {
		this.timeInstant = timeInstant;
	}

	
	@Column(name = "time_period_start", length = 29)
	public String getTimePeriodStart() {
		return this.timePeriodStart;
	}

	public void setTimePeriodStart(String timePeriodStart) {
		this.timePeriodStart = timePeriodStart;
	}

	
	@Column(name = "time_period_end", length = 29)
	public String getTimePeriodEnd() {
		return this.timePeriodEnd;
	}

	public void setTimePeriodEnd(String timePeriodEnd) {
		this.timePeriodEnd = timePeriodEnd;
	}



}
