package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resources generated by hbm2java
 */
@Entity
@Table(name = "resources")
public class Resources implements java.io.Serializable {

	private String resourceIdentifier;
	private Location location;
	private LogDate logDate;
	private Method method;
	private ResourceDate resourceDate;
	private String registeredObjectType;
	private String landingPage;
	private Boolean isPublic;
	private String resourceTitle;
	private String purpose;
	private String campaign;
	private String comments;
	private Set<Contributors> contributorses = new HashSet<Contributors>(0);
	private Set<RelatedResources> relatedResourceses = new HashSet<RelatedResources>(
			0);
	private Set<AlternateIdentifiers> alternateIdentifierses = new HashSet<AlternateIdentifiers>(
			0);
	private Set<Classifications> classificationses = new HashSet<Classifications>(
			0);
	private Set<ResourceTypes> resourceTypeses = new HashSet<ResourceTypes>(0);
	private Set<SampledFeatures> sampledFeatureses = new HashSet<SampledFeatures>(
			0);
	private Set<Collectors> collectorses = new HashSet<Collectors>(0);
	private Set<CurationDetails> curationDetailses = new HashSet<CurationDetails>(
			0);
	private Set<MaterialTypes> materialTypeses = new HashSet<MaterialTypes>(0);

	public Resources() {
	}

	public Resources(String resourceIdentifier) {
		this.resourceIdentifier = resourceIdentifier;
	}

	public Resources(String resourceIdentifier, Location location,
			LogDate logDate, Method method, ResourceDate resourceDate,
			String registeredObjectType, String landingPage, Boolean isPublic,
			String resourceTitle, String purpose, String campaign,
			String comments, Set<Contributors> contributorses,
			Set<RelatedResources> relatedResourceses,
			Set<AlternateIdentifiers> alternateIdentifierses,
			Set<Classifications> classificationses,
			Set<ResourceTypes> resourceTypeses,
			Set<SampledFeatures> sampledFeatureses,
			Set<Collectors> collectorses,
			Set<CurationDetails> curationDetailses,
			Set<MaterialTypes> materialTypeses) {
		this.resourceIdentifier = resourceIdentifier;
		this.location = location;
		this.logDate = logDate;
		this.method = method;
		this.resourceDate = resourceDate;
		this.registeredObjectType = registeredObjectType;
		this.landingPage = landingPage;
		this.isPublic = isPublic;
		this.resourceTitle = resourceTitle;
		this.purpose = purpose;
		this.campaign = campaign;
		this.comments = comments;
		this.contributorses = contributorses;
		this.relatedResourceses = relatedResourceses;
		this.alternateIdentifierses = alternateIdentifierses;
		this.classificationses = classificationses;
		this.resourceTypeses = resourceTypeses;
		this.sampledFeatureses = sampledFeatureses;
		this.collectorses = collectorses;
		this.curationDetailses = curationDetailses;
		this.materialTypeses = materialTypeses;
	}

	@Id
	@Column(name = "resource_identifier", unique = true, nullable = false)
	public String getResourceIdentifier() {
		return this.resourceIdentifier;
	}

	public void setResourceIdentifier(String resourceIdentifier) {
		this.resourceIdentifier = resourceIdentifier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id")
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "log_date_id")
	public LogDate getLogDate() {
		return this.logDate;
	}

	public void setLogDate(LogDate logDate) {
		this.logDate = logDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "method_id")
	public Method getMethod() {
		return this.method;
	}

	public void setMethod(Method method) {
		this.method = method;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "date")
	public ResourceDate getResourceDate() {
		return this.resourceDate;
	}

	public void setResourceDate(ResourceDate resourceDate) {
		this.resourceDate = resourceDate;
	}

	@Column(name = "registered_object_type")
	public String getRegisteredObjectType() {
		return this.registeredObjectType;
	}

	public void setRegisteredObjectType(String registeredObjectType) {
		this.registeredObjectType = registeredObjectType;
	}

	@Column(name = "landing_page")
	public String getLandingPage() {
		return this.landingPage;
	}

	public void setLandingPage(String landingPage) {
		this.landingPage = landingPage;
	}

	@Column(name = "is_public")
	public Boolean getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

	@Column(name = "resource_title")
	public String getResourceTitle() {
		return this.resourceTitle;
	}

	public void setResourceTitle(String resourceTitle) {
		this.resourceTitle = resourceTitle;
	}

	@Column(name = "purpose")
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Column(name = "campaign")
	public String getCampaign() {
		return this.campaign;
	}

	public void setCampaign(String campaign) {
		this.campaign = campaign;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<Contributors> getContributorses() {
		return this.contributorses;
	}

	public void setContributorses(Set<Contributors> contributorses) {
		this.contributorses = contributorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<RelatedResources> getRelatedResourceses() {
		return this.relatedResourceses;
	}

	public void setRelatedResourceses(Set<RelatedResources> relatedResourceses) {
		this.relatedResourceses = relatedResourceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<AlternateIdentifiers> getAlternateIdentifierses() {
		return this.alternateIdentifierses;
	}

	public void setAlternateIdentifierses(
			Set<AlternateIdentifiers> alternateIdentifierses) {
		this.alternateIdentifierses = alternateIdentifierses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<Classifications> getClassificationses() {
		return this.classificationses;
	}

	public void setClassificationses(Set<Classifications> classificationses) {
		this.classificationses = classificationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<ResourceTypes> getResourceTypeses() {
		return this.resourceTypeses;
	}

	public void setResourceTypeses(Set<ResourceTypes> resourceTypeses) {
		this.resourceTypeses = resourceTypeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<SampledFeatures> getSampledFeatureses() {
		return this.sampledFeatureses;
	}

	public void setSampledFeatureses(Set<SampledFeatures> sampledFeatureses) {
		this.sampledFeatureses = sampledFeatureses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<Collectors> getCollectorses() {
		return this.collectorses;
	}

	public void setCollectorses(Set<Collectors> collectorses) {
		this.collectorses = collectorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<CurationDetails> getCurationDetailses() {
		return this.curationDetailses;
	}

	public void setCurationDetailses(Set<CurationDetails> curationDetailses) {
		this.curationDetailses = curationDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resources")
	public Set<MaterialTypes> getMaterialTypeses() {
		return this.materialTypeses;
	}

	public void setMaterialTypeses(Set<MaterialTypes> materialTypeses) {
		this.materialTypeses = materialTypeses;
	}

}
