package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ResourceTypes generated by hbm2java
 */
@Entity
@Table(name = "resource_types")
public class ResourceTypes implements java.io.Serializable {

	private int resourceTypeId;
	private CvResourceType cvResourceType;
	private Resources resources;

	public ResourceTypes() {
	}

	public ResourceTypes(Resources resources,CvResourceType cvResourceType) {		
		this.cvResourceType = cvResourceType;
		this.resources = resources;
	}

	@Id
	@Column(name = "resource_type_id", unique = true, nullable = false)
	@SequenceGenerator(name="resource_type_id_seq",schema="version30",sequenceName="resource_type_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="resource_type_id_seq")
	public int getResourceTypeId() {
		return this.resourceTypeId;
	}

	public void setResourceTypeId(int resourceTypeId) {
		this.resourceTypeId = resourceTypeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "resource_type")
	public CvResourceType getCvResourceType() {
		return this.cvResourceType;
	}

	public void setCvResourceType(CvResourceType cvResourceType) {
		this.cvResourceType = cvResourceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_identifier")
	@JsonIgnore
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

}
