package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResourceDate generated by hbm2java
 */
@Entity
@Table(name = "resource_date")
public class ResourceDate implements java.io.Serializable {

	private int resourceDateId;
	private Date timeInstant;
	private Date timePeriodStart;
	private Date timePeriodEnd;
	private Set<Resources> resourceses = new HashSet<Resources>(0);

	public ResourceDate() {
	}


	public ResourceDate(Date timeInstant,
			Date timePeriodStart, Date timePeriodEnd, Set<Resources> resourceses) {	
		this.timeInstant = timeInstant;
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = timePeriodEnd;
		this.resourceses = resourceses;
	}

	@Id
	@Column(name = "resource_date_id", unique = true, nullable = false)
	@SequenceGenerator(name="resource_date_id_seq",schema="version30",sequenceName="resource_date_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="resource_date_id_seq")
	public int getResourceDateId() {
		return this.resourceDateId;
	}

	public void setResourceDateId(int resourceDateId) {
		this.resourceDateId = resourceDateId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_instant", length = 29)
	public Date getTimeInstant() {
		return this.timeInstant;
	}

	public void setTimeInstant(Date timeInstant) {
		this.timeInstant = timeInstant;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_period_start", length = 29)
	public Date getTimePeriodStart() {
		return this.timePeriodStart;
	}

	public void setTimePeriodStart(Date timePeriodStart) {
		this.timePeriodStart = timePeriodStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_period_end", length = 29)
	public Date getTimePeriodEnd() {
		return this.timePeriodEnd;
	}

	public void setTimePeriodEnd(Date timePeriodEnd) {
		this.timePeriodEnd = timePeriodEnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceDate")
	public Set<Resources> getResourceses() {
		return this.resourceses;
	}

	public void setResourceses(Set<Resources> resourceses) {
		this.resourceses = resourceses;
	}

}
