package org.csiro.igsn.entity.postgres;

// Generated 09/01/2017 4:40:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * SampledFeatures generated by hbm2java
 */
@Entity
@Table(name = "sampled_features")
public class SampledFeatures implements java.io.Serializable {

	private int sampledFeaturesId;
	private Resources resources;
	private String sampledFeatureUri;
	private String sampledFeature;

	public SampledFeatures() {
	}



	public SampledFeatures(Resources resources,
			String sampledFeatureUri, String sampledFeature) {		
		this.resources = resources;
		this.sampledFeatureUri = sampledFeatureUri;
		this.sampledFeature = sampledFeature;
	}

	@Id
	@Column(name = "sampled_features_id", unique = true, nullable = false)
	@SequenceGenerator(name="sampled_features_id_seq",schema="version30",sequenceName="sampled_features_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="sampled_features_id_seq")
	public int getSampledFeaturesId() {
		return this.sampledFeaturesId;
	}

	public void setSampledFeaturesId(int sampledFeaturesId) {
		this.sampledFeaturesId = sampledFeaturesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_identifier")
	@JsonIgnore
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	@Column(name = "sampled_feature_uri")
	public String getSampledFeatureUri() {
		return this.sampledFeatureUri;
	}

	public void setSampledFeatureUri(String sampledFeatureUri) {
		this.sampledFeatureUri = sampledFeatureUri;
	}

	@Column(name = "sampled_feature")
	public String getSampledFeature() {
		return this.sampledFeature;
	}

	public void setSampledFeature(String sampledFeature) {
		this.sampledFeature = sampledFeature;
	}

}
