//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 11:28:08 AM AWST 
//


package org.csiro.igsn.jaxb.registration.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csiro.igsn.jaxb.registration.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResourcesResourceLocation_QNAME = new QName("https://igsn.csiro.au/schemas/3.0", "location");
    private final static QName _ResourcesResourceSampledFeatures_QNAME = new QName("https://igsn.csiro.au/schemas/3.0", "sampledFeatures");
    private final static QName _ResourcesResourceDate_QNAME = new QName("https://igsn.csiro.au/schemas/3.0", "date");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csiro.igsn.jaxb.registration.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link Resources.Resource }
     * 
     */
    public Resources.Resource createResourcesResource() {
        return new Resources.Resource();
    }

    /**
     * Create an instance of {@link Resources.Resource.RelatedResources }
     * 
     */
    public Resources.Resource.RelatedResources createResourcesResourceRelatedResources() {
        return new Resources.Resource.RelatedResources();
    }

    /**
     * Create an instance of {@link Resources.Resource.Contributors }
     * 
     */
    public Resources.Resource.Contributors createResourcesResourceContributors() {
        return new Resources.Resource.Contributors();
    }

    /**
     * Create an instance of {@link Resources.Resource.Contributors.Contributor }
     * 
     */
    public Resources.Resource.Contributors.Contributor createResourcesResourceContributorsContributor() {
        return new Resources.Resource.Contributors.Contributor();
    }

    /**
     * Create an instance of {@link Resources.Resource.CurationDetails }
     * 
     */
    public Resources.Resource.CurationDetails createResourcesResourceCurationDetails() {
        return new Resources.Resource.CurationDetails();
    }

    /**
     * Create an instance of {@link Resources.Resource.CurationDetails.Curation }
     * 
     */
    public Resources.Resource.CurationDetails.Curation createResourcesResourceCurationDetailsCuration() {
        return new Resources.Resource.CurationDetails.Curation();
    }

    /**
     * Create an instance of {@link Resources.Resource.Date }
     * 
     */
    public Resources.Resource.Date createResourcesResourceDate() {
        return new Resources.Resource.Date();
    }

    /**
     * Create an instance of {@link Resources.Resource.Location }
     * 
     */
    public Resources.Resource.Location createResourcesResourceLocation() {
        return new Resources.Resource.Location();
    }

    /**
     * Create an instance of {@link Resources.Resource.SampledFeatures }
     * 
     */
    public Resources.Resource.SampledFeatures createResourcesResourceSampledFeatures() {
        return new Resources.Resource.SampledFeatures();
    }

    /**
     * Create an instance of {@link Resources.Resource.Classifications }
     * 
     */
    public Resources.Resource.Classifications createResourcesResourceClassifications() {
        return new Resources.Resource.Classifications();
    }

    /**
     * Create an instance of {@link Resources.Resource.ResourceIdentifier }
     * 
     */
    public Resources.Resource.ResourceIdentifier createResourcesResourceResourceIdentifier() {
        return new Resources.Resource.ResourceIdentifier();
    }

    /**
     * Create an instance of {@link Resources.Resource.IsPublic }
     * 
     */
    public Resources.Resource.IsPublic createResourcesResourceIsPublic() {
        return new Resources.Resource.IsPublic();
    }

    /**
     * Create an instance of {@link Resources.Resource.AlternateIdentifiers }
     * 
     */
    public Resources.Resource.AlternateIdentifiers createResourcesResourceAlternateIdentifiers() {
        return new Resources.Resource.AlternateIdentifiers();
    }

    /**
     * Create an instance of {@link Resources.Resource.ResourceTypes }
     * 
     */
    public Resources.Resource.ResourceTypes createResourcesResourceResourceTypes() {
        return new Resources.Resource.ResourceTypes();
    }

    /**
     * Create an instance of {@link Resources.Resource.MaterialTypes }
     * 
     */
    public Resources.Resource.MaterialTypes createResourcesResourceMaterialTypes() {
        return new Resources.Resource.MaterialTypes();
    }

    /**
     * Create an instance of {@link Resources.Resource.Method }
     * 
     */
    public Resources.Resource.Method createResourcesResourceMethod() {
        return new Resources.Resource.Method();
    }

    /**
     * Create an instance of {@link Resources.Resource.LogDate }
     * 
     */
    public Resources.Resource.LogDate createResourcesResourceLogDate() {
        return new Resources.Resource.LogDate();
    }

    /**
     * Create an instance of {@link Resources.Resource.RelatedResources.RelatedResource }
     * 
     */
    public Resources.Resource.RelatedResources.RelatedResource createResourcesResourceRelatedResourcesRelatedResource() {
        return new Resources.Resource.RelatedResources.RelatedResource();
    }

    /**
     * Create an instance of {@link Resources.Resource.Contributors.Contributor.ContributorIdentifier }
     * 
     */
    public Resources.Resource.Contributors.Contributor.ContributorIdentifier createResourcesResourceContributorsContributorContributorIdentifier() {
        return new Resources.Resource.Contributors.Contributor.ContributorIdentifier();
    }

    /**
     * Create an instance of {@link Resources.Resource.CurationDetails.Curation.CuratingInstitution }
     * 
     */
    public Resources.Resource.CurationDetails.Curation.CuratingInstitution createResourcesResourceCurationDetailsCurationCuratingInstitution() {
        return new Resources.Resource.CurationDetails.Curation.CuratingInstitution();
    }

    /**
     * Create an instance of {@link Resources.Resource.Date.TimePeriod }
     * 
     */
    public Resources.Resource.Date.TimePeriod createResourcesResourceDateTimePeriod() {
        return new Resources.Resource.Date.TimePeriod();
    }

    /**
     * Create an instance of {@link Resources.Resource.Location.Locality }
     * 
     */
    public Resources.Resource.Location.Locality createResourcesResourceLocationLocality() {
        return new Resources.Resource.Location.Locality();
    }

    /**
     * Create an instance of {@link Resources.Resource.Location.Geometry }
     * 
     */
    public Resources.Resource.Location.Geometry createResourcesResourceLocationGeometry() {
        return new Resources.Resource.Location.Geometry();
    }

    /**
     * Create an instance of {@link Resources.Resource.SampledFeatures.SampledFeature }
     * 
     */
    public Resources.Resource.SampledFeatures.SampledFeature createResourcesResourceSampledFeaturesSampledFeature() {
        return new Resources.Resource.SampledFeatures.SampledFeature();
    }

    /**
     * Create an instance of {@link Resources.Resource.Classifications.Classification }
     * 
     */
    public Resources.Resource.Classifications.Classification createResourcesResourceClassificationsClassification() {
        return new Resources.Resource.Classifications.Classification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resources.Resource.Location }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://igsn.csiro.au/schemas/3.0", name = "location", scope = Resources.Resource.class)
    public JAXBElement<Resources.Resource.Location> createResourcesResourceLocation(Resources.Resource.Location value) {
        return new JAXBElement<Resources.Resource.Location>(_ResourcesResourceLocation_QNAME, Resources.Resource.Location.class, Resources.Resource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resources.Resource.SampledFeatures }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://igsn.csiro.au/schemas/3.0", name = "sampledFeatures", scope = Resources.Resource.class)
    public JAXBElement<Resources.Resource.SampledFeatures> createResourcesResourceSampledFeatures(Resources.Resource.SampledFeatures value) {
        return new JAXBElement<Resources.Resource.SampledFeatures>(_ResourcesResourceSampledFeatures_QNAME, Resources.Resource.SampledFeatures.class, Resources.Resource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resources.Resource.Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://igsn.csiro.au/schemas/3.0", name = "date", scope = Resources.Resource.class)
    public JAXBElement<Resources.Resource.Date> createResourcesResourceDate(Resources.Resource.Date value) {
        return new JAXBElement<Resources.Resource.Date>(_ResourcesResourceDate_QNAME, Resources.Resource.Date.class, Resources.Resource.class, value);
    }

}
